version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: realmatch_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - realmatch-network

  redis:
    image: redis:alpine
    container_name: realmatch_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - realmatch-network

  app:
    image: ${DOCKERHUB_USERNAME}/realmatch-backend:prod
    # build:          # 이건 DEV 환경에서 사용해주세요
    #   context: .
    #   dockerfile: Docker/Dockerfile
    container_name: realmatch_spring
    restart: always
    ports:
      - "8080:6000"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    networks:
      - realmatch-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: realmatch_mqtt
    restart: always
    ports:
      - ${RABBITMQ_MQ_PORT}:${RABBITMQ_MQ_PORT}    # for mq
      - ${RABBITMQ_WEB_PORT}:${RABBITMQ_WEB_PORT}  # for webpage
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - realmatch-network

networks:
  realmatch-network:
    driver: bridge