cors:
  allowed-origin: http://${SERVER_IP}

swagger:
  server-url: ${SWAGGER_SERVER_URL}

server:
  timezone: Asia/Seoul

spring:
  application:
    name: Spot
  activate:
    on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 10000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    refresh-token:
      expire-days: 14

logging:
  level:
    org.hibernate.SQL: warn

jwt:
  secret: ${JWT_SECRET}
  access-expire-ms: ${JWT_ACCESS_EXPIRE_MS}
  refresh-expire-ms: ${JWT_REFRESH_EXPIRE_MS}

