spring:
  application:
    name: Spot

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  security:
    refresh-token:
      expire-days: 14

jwt:
  secret: ${JWT_SECRET}
  access-expire-ms: ${JWT_ACCESS_EXPIRE_MS}
  refresh-expire-ms: ${JWT_REFRESH_EXPIRE_MS}
